# bundle.py
import os

FOLDER = "MinigameAutomation"
OUTPUT = "Main.lua"

ORDER = [
    "Config.lua",
    "State.lua",
    "Services.lua",
    "VisualsInit.lua",
    "GuiHelpers.lua",
    "GuiSetup.lua",
    "TicketScanner.lua",
    "Keybinds.lua",
    "BiomeLogs.lua",
    "GuiDragging.lua",
    "PathContextMenu.lua",
    "UiStateController.lua",
    "AutoBox.lua",
    "PathVisualization.lua",
    "WatermelonTracker.lua",
    "InteractionHelpers.lua",
    "WatermelonPromptHandler.lua",
    "AutoEquip.lua",
    "AutoDevice.lua",
    "PathfindingEngine.lua",
    "AutomationSequences.lua",
    "ControllerExecution.lua",
]

def main():
    lines = []
    lines.append("-- Bundled MinigameAutomation")
    lines.append("-- Generated by bundle.py")
    lines.append("")

    for filename in ORDER:
        path = os.path.join(FOLDER, filename)
        if not os.path.isfile(path):
            print(f"Warning: {path} not found, skipping.")
            continue

        with open(path, "r", encoding="utf-8") as f:
            content = f.read()

        lines.append(f"-- ===== {filename} =====")
        lines.append(content)
        lines.append("")

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Bundled into {OUTPUT}")

if __name__ == "__main__":
    main()