# bundle.py
import os

FOLDER = "MinigameAutomation"
OUTPUT = "Main.lua"


def main():
    lines = [
        "-- Bundled MinigameAutomation",
        "-- Generated by bundle.py",
        "",
    ]

    if not os.path.isdir(FOLDER):
        print(f"Error: folder '{FOLDER}' not found.")
        return

    # Get all .lua files in the folder
    lua_files = [f for f in os.listdir(FOLDER) if f.endswith(".lua")]

    # Optional: sort alphabetically; remove sorted() if you want raw OS order
    lua_files = sorted(lua_files)

    for filename in lua_files:
        path = os.path.join(FOLDER, filename)
        if not os.path.isfile(path):
            print(f"Warning: {path} not found, skipping.")
            continue

        with open(path, "r", encoding="utf-8") as f:
            content = f.read()

        lines.append(f"-- ===== {filename} =====")
        lines.append(content)
        lines.append("")

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Bundled {len(lua_files)} file(s) into {OUTPUT}")


if __name__ == "__main__":
    main()