-- Bundled MinigameAutomation
-- Generated by bundle.py

-- ===== Config.lua =====
-- CONFIG

local WATERMELON_NAME = "watermelon"
local SCAN_INTERVAL = 1

local VISUAL_FOLDER_NAME = "_DevWatermelonVisuals"
local PATH_VISUAL_FOLDER_NAME = "_PathVisuals"

local BOX_COLOR = Color3.fromRGB(220, 225, 235)
local OUTLINE_COLOR = Color3.fromRGB(255, 255, 255)
local PATH_COLOR = Color3.fromRGB(180, 210, 255)

local MAX_CONSECUTIVE_FAILURES = 5
local PATH_OPTIONS = {
    AgentRadius = 2,
    AgentHeight = 5,
    AgentCanJump = true,
    WaypointSpacing = 4,
}

-- ===== State.lua =====
-- STATE

local boxesEnabled = true
local pathfindingEnabled = false
local viewPathEnabled = false
local autoJumpEnabled = true
local autoEquipEnabled = false
local autoDeviceEnabled = false

local trackedWatermelons = {}

local routineToken = 0
local activeRoutine = false
local consecutivePathFailures = 0

-- ===== Services.lua =====
-- SERVICES

local Workspace = game:GetService("Workspace")
local Players = game:GetService("Players")
local PathfindingService = game:GetService("PathfindingService")
local UserInputService = game:GetService("UserInputService")
local VirtualInputManager = game:GetService("VirtualInputManager")
local GuiService = game:GetService("GuiService")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")
local Event = game:GetService("ReplicatedStorage").ByteNetReliable

local Camera = Workspace:FindFirstChildOfClass("Camera")

local player = Players.LocalPlayer
local playerGui = player:WaitForChild("PlayerGui")

local playerGui2 = Players.LocalPlayer:WaitForChild("PlayerGui")

local TOGGLE_KEY = Enum.KeyCode.LeftAlt

local TextChatService = game:GetService("TextChatService")

local LocalPlayer = Players.LocalPlayer

-- ===== VisualsInit.lua =====
-- CLEAN UP OLD UI / VISUALS + CREATE FOLDERS

local oldGui = playerGui:FindFirstChild("WatermelonTrackerGui")
if oldGui then
    oldGui:Destroy()
end

local oldVisualFolder = Workspace:FindFirstChild(VISUAL_FOLDER_NAME)
if oldVisualFolder then
    oldVisualFolder:Destroy()
end

local oldPathFolder = Workspace:FindFirstChild(PATH_VISUAL_FOLDER_NAME)
if oldPathFolder then
    oldPathFolder:Destroy()
end

local visualFolder = Instance.new("Folder")
visualFolder.Name = VISUAL_FOLDER_NAME
visualFolder.Parent = Workspace

local pathVisualFolder = Instance.new("Folder")
pathVisualFolder.Name = PATH_VISUAL_FOLDER_NAME
pathVisualFolder.Parent = Workspace

-- ===== GuiHelpers.lua =====
-- GUI HELPERS (LIQUID GLASS STYLES)

local function addCorner(parent, radius)
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, radius)
    corner.Parent = parent
    return corner
end

local function addGlassStroke(parent, transparency, thickness)
    local stroke = Instance.new("UIStroke")
    stroke.Color = Color3.fromRGB(255, 255, 255)
    stroke.Transparency = transparency
    stroke.Thickness = thickness
    stroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
    stroke.Parent = parent
    return stroke
end

local function addGlassGradient(parent)
    local gradient = Instance.new("UIGradient")
    gradient.Color = ColorSequence.new({
        ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
        ColorSequenceKeypoint.new(1, Color3.fromRGB(150, 160, 180))
    })
    gradient.Transparency = NumberSequence.new({
        NumberSequenceKeypoint.new(0, 0.75),
        NumberSequenceKeypoint.new(1, 0.90)
    })
    gradient.Rotation = 45
    gradient.Parent = parent
    return gradient
end

-- ===== GuiSetup.lua =====
-- GUI SETUP

local screenGui = Instance.new("ScreenGui")
screenGui.Name = "WatermelonTrackerGui"
screenGui.ResetOnSpawn = false
screenGui.IgnoreGuiInset = false
screenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
screenGui.Parent = playerGui

local frame = Instance.new("Frame")
frame.Name = "MainFrame"
frame.Size = UDim2.fromOffset(240, 0)
frame.AutomaticSize = Enum.AutomaticSize.Y
frame.Position = UDim2.new(0.02, 0, 0.20, 0)
frame.BackgroundColor3 = Color3.fromRGB(15, 17, 23)
frame.BackgroundTransparency = 0.25
frame.BorderSizePixel = 0
frame.Active = true
frame.Draggable = false
frame.Parent = screenGui
addCorner(frame, 16)
addGlassStroke(frame, 0.7, 1)
addGlassGradient(frame)

local framePadding = Instance.new("UIPadding")
framePadding.PaddingTop = UDim.new(0, 12)
framePadding.PaddingBottom = UDim.new(0, 12)
framePadding.PaddingLeft = UDim.new(0, 12)
framePadding.PaddingRight = UDim.new(0, 12)
framePadding.Parent = frame

local listLayout = Instance.new("UIListLayout")
listLayout.SortOrder = Enum.SortOrder.LayoutOrder
listLayout.Padding = UDim.new(0, 8)
listLayout.Parent = frame

local titleLabel = Instance.new("TextLabel")
titleLabel.Name = "Title"
titleLabel.Size = UDim2.new(1, 0, 0, 20)
titleLabel.BackgroundTransparency = 1
titleLabel.Text = "Watermelon Bot"
titleLabel.TextColor3 = Color3.fromRGB(240, 243, 250)
titleLabel.Font = Enum.Font.GothamBold
titleLabel.TextSize = 14
titleLabel.TextXAlignment = Enum.TextXAlignment.Left
titleLabel.LayoutOrder = 1
titleLabel.Parent = frame

local statusLabel = Instance.new("TextLabel")
statusLabel.Name = "Status"
statusLabel.Size = UDim2.new(1, 0, 0, 16)
statusLabel.BackgroundTransparency = 1
statusLabel.Text = "Status: Idle"
statusLabel.TextColor3 = Color3.fromRGB(160, 168, 185)
statusLabel.Font = Enum.Font.GothamMedium
statusLabel.TextSize = 11
statusLabel.TextXAlignment = Enum.TextXAlignment.Left
statusLabel.LayoutOrder = 2
statusLabel.Parent = frame

local attemptsLabel = Instance.new("TextLabel")
attemptsLabel.Name = "AttemptsLabel"
attemptsLabel.Size = UDim2.new(1, 0, 0, 16)
attemptsLabel.BackgroundTransparency = 1
attemptsLabel.Text = "⚠ 0 Attempts"
attemptsLabel.TextColor3 = Color3.fromRGB(255, 200, 100)
attemptsLabel.Font = Enum.Font.GothamMedium
attemptsLabel.TextSize = 11
attemptsLabel.TextXAlignment = Enum.TextXAlignment.Center
attemptsLabel.LayoutOrder = 3
attemptsLabel.Parent = frame

local function makeButton(name, text, layoutOrder)
    local button = Instance.new("TextButton")
    button.Name = name
    button.Size = UDim2.new(1, 0, 0, 38)
    button.LayoutOrder = layoutOrder
    button.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    button.BackgroundTransparency = 0.92
    button.BorderSizePixel = 0
    button.Text = text
    button.TextColor3 = Color3.fromRGB(235, 240, 250)
    button.Font = Enum.Font.GothamSemibold
    button.TextSize = 12
    button.AutoButtonColor = false
    button.Parent = frame
    addCorner(button, 10)
    addGlassStroke(button, 0.82, 1)
    return button
end

local toggleBoxesButton = makeButton("ToggleBoxesButton", "Bounding Boxes: ON", 4)
local togglePathButton = makeButton("TogglePathButton", "Pathfinding: OFF", 5)
local autoDeviceButton = makeButton("AutoDeviceButton", "Auto-Device: OFF", 6)

local dropdownArrow = Instance.new("TextLabel")
dropdownArrow.Name = "DropdownArrow"
dropdownArrow.Size = UDim2.fromOffset(30, 30)
dropdownArrow.Position = UDim2.new(1, -30, 0.5, -15)
dropdownArrow.BackgroundTransparency = 1
dropdownArrow.Text = "▼"
dropdownArrow.TextColor3 = Color3.fromRGB(180, 190, 210)
dropdownArrow.Font = Enum.Font.GothamBold
dropdownArrow.TextSize = 10
dropdownArrow.Parent = togglePathButton

-- ===== TicketScanner.lua =====
-- TICKET SCANNER & ATTEMPTS UPDATER

local function updateAttemptsUI()
    local mainInterface = playerGui:FindFirstChild("MainInterface")
    if not mainInterface then
        attemptsLabel.Text = "⚠ 0 Attempts"
        return
    end

    local itemGridScrollingFrame = mainInterface:FindFirstChild("Inventory")
        and mainInterface.Inventory:FindFirstChild("Items")
        and mainInterface.Inventory.Items:FindFirstChild("ItemGrid")
        and mainInterface.Inventory.Items.ItemGrid:FindFirstChild("ItemGridScrollingFrame")

    if not itemGridScrollingFrame then
        attemptsLabel.Text = "⚠ 0 Attempts"
        return
    end

    local minigameTicket = itemGridScrollingFrame:FindFirstChild("Item\010minigame_ticket") 
        or itemGridScrollingFrame:FindFirstChild("Item\nminigame_ticket")

    if minigameTicket then
        local button = minigameTicket:FindFirstChild("Button")
        if button then
            local itemAmount = button:FindFirstChild("ItemAmount")
            if itemAmount then
                local rawText = itemAmount.Text
                local count = string.match(rawText, "%d+") or "0"
                attemptsLabel.Text = "⚠ " .. count .. " Attempts"
                return
            end
        end
    end

    attemptsLabel.Text = "⚠ 0 Attempts"
end

task.spawn(function()
    local mainInterface = playerGui:WaitForChild("MainInterface", 10)
    if not mainInterface then return end

    local itemGridScrollingFrame = mainInterface:WaitForChild("Inventory", 5)
        and mainInterface.Inventory:WaitForChild("Items", 5)
        and mainInterface.Inventory.Items:WaitForChild("ItemGrid", 5)
        and mainInterface.Inventory.Items.ItemGrid:WaitForChild("ItemGridScrollingFrame", 5)

    if itemGridScrollingFrame then
        local minigameTicket = itemGridScrollingFrame:FindFirstChild("Item\010minigame_ticket") 
            or itemGridScrollingFrame:FindFirstChild("Item\nminigame_ticket")

        if minigameTicket then
            local button = minigameTicket:WaitForChild("Button", 5)
            if button then
                local itemAmount = button:WaitForChild("ItemAmount", 5)
                if itemAmount then
                    itemAmount:GetPropertyChangedSignal("Text"):Connect(function()
                        updateAttemptsUI()
                    end)
                end
            end
        end
    end
end)

updateAttemptsUI()

-- ===== Keybinds.lua =====
local function toggleGuiVisibility()
    local watermelonGui = playerGui:FindFirstChild("WatermelonTrackerGui")
    local biomeGui = playerGui:FindFirstChild("BiomeTrackerGui")
    
    if watermelonGui then
        watermelonGui.Enabled = not watermelonGui.Enabled
    end
    
    if biomeGui then
        biomeGui.Enabled = not biomeGui.Enabled
    end
end

-- Process core input connection listener
UserInputService.InputBegan:Connect(function(input, gameProcessed)
    -- Do not trigger if typing in standard chat windows
    if gameProcessed then return end
    
    if input.KeyCode == TOGGLE_KEY then
        toggleGuiVisibility()
    end
end)


-- ===== BiomeLogs.lua =====
-- ===== BIOME LOGS & GUI SYSTEM (PART 1 OF 4) =====
local TextChatService = game:GetService("TextChatService")
local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer
local playerGui = LocalPlayer:WaitForChild("PlayerGui")

-- Helper to safely capture text variations
local function escapePattern(str)
    return str:gsub("([^%w])", "%%%1")
end

-- 1. BIOME DEFINITION CONFIG (Ordered exactly as requested with Wiki colors)
local BIOME_CONFIG = {
    { ID = "Cyberspace",  Color = Color3.fromRGB(0, 100, 255),   Text = "Cyberspace" },
    { ID = "Dreamspace",  Color = Color3.fromRGB(255, 140, 200),  Text = "Dreammetric" }, 
    { ID = "Glitched",    Color = Color3.fromRGB(0, 255, 180),    Text = "Glitch" },
    { ID = "Singularity", Color = Color3.fromRGB(130, 50, 255),   Text = "Singularity" },
    { ID = "Null",        Color = Color3.fromRGB(150, 150, 150),  Text = "Null" },
    { ID = "Corruption",  Color = Color3.fromRGB(180, 70, 255),   Text = "Corruption" },
    { ID = "Heaven",      Color = Color3.fromRGB(255, 230, 100),  Text = "Heaven" },
    { ID = "Starfall",    Color = Color3.fromRGB(90, 160, 255),   Text = "Starfall" },
    { ID = "Hell",        Color = Color3.fromRGB(255, 60, 60),    Text = "Hell" },
    { ID = "Sandstorm",   Color = Color3.fromRGB(240, 200, 110),  Text = "Sandstorm" },
    { ID = "Rainy",       Color = Color3.fromRGB(140, 170, 190),  Text = "Rainy" },
    { ID = "Snowy",       Color = Color3.fromRGB(200, 235, 255),  Text = "Snowy" },
    { ID = "Windy",       Color = Color3.fromRGB(170, 255, 230),  Text = "Windy" },
    { ID = "Blazing Sun", Color = Color3.fromRGB(236, 230, 46),   Text = "Blazing Sun" },
    { ID = "Incinerator", Color = Color3.fromRGB(206, 128, 0),    Text = "Incinerator" }
}

-- Operational State Data Storage
local biomeCounters = {}
_G.BiomeFilterStates = {} 

for _, config in ipairs(BIOME_CONFIG) do
    biomeCounters[config.ID] = 0
    _G.BiomeFilterStates[config.ID] = true 
end
-- ===== BIOME LOGS & GUI SYSTEM (PART 2 OF 4) =====

-- Biome Data Mapping Table (Using your exact updated rules and entries)
local BIOME_DICTIONARY = {
    -- Normal Biomes
    ["A refreshing and cool wind passes through the world"] = "Windy",
    ["White snow and cold begin to cover the surroundings"] = "Snowy",
    ["Strong winds and showers sweep through the world"] = "Rainy",
    ["A harsh Sand Storm blocks your path"] = "Sandstorm",
    ["A strong and violent energy of chaos overtakes the world"] = "Hell",
    ["Beautiful and dreamy starlight pours into the world"] = "Starfall",
    ["A hand of angel leads you into divine place"] = "Heaven",
    ["Poisonous pollution spreads throughout the world"] = "Corruption",
    ["It's too dark here"] = "Null",
    
    -- Rare Biomes
    ["Unexpected error occurred. [Code 404]"] = "Glitched",
    ["[Code 404] has resolved."] = "Normal (Glitched Ended)",
    ["You begin to feel sleepy"] = "Dreamspace",
    ["Waking up"] = "Normal (Dreamspace Ended)",
    ["Signal_Received | From: Island_SOL"] = "Cyberspace",
    ["Signal Lost."] = "Normal (Cyberspace Ended)",
    ["The Singularity pulls in everything, including you"] = "Singularity",
    
    -- Event Biomes
    ["The hot sunlight begins to shine on you"] = "Blazing Sun",
    ["It's hotter than usual today! It's a heatwave!"] = "Incinerator"
}

-- 2. LIQUID GLASS UI STRUCTURING STYLES
local function addCorner(parent, radius)
    local corner = Instance.new("UICorner")
    corner.CornerRadius = UDim.new(0, radius)
    corner.Parent = parent
end

local function addGlassStroke(parent, transparency, thickness)
    local stroke = Instance.new("UIStroke")
    stroke.Color = Color3.fromRGB(255, 255, 255)
    stroke.Transparency = transparency
    stroke.Thickness = thickness
    stroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
    stroke.Parent = parent
end

local function addGlassGradient(parent)
    local gradient = Instance.new("UIGradient")
    gradient.Color = ColorSequence.new({
        ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)),
        ColorSequenceKeypoint.new(1, Color3.fromRGB(150, 160, 180))
    })
    gradient.Transparency = NumberSequence.new({
        NumberSequenceKeypoint.new(0, 0.75),
        NumberSequenceKeypoint.new(1, 0.90)
    })
    gradient.Rotation = 45
    gradient.Parent = parent
end
-- ===== BIOME LOGS & GUI SYSTEM (PART 3 OF 4) =====

-- 3. INTERACTIVE MAIN WINDOW BUILDER
if playerGui:FindFirstChild("BiomeTrackerGui") then
    playerGui.BiomeTrackerGui:Destroy()
end

local screenGui = Instance.new("ScreenGui")
screenGui.Name = "BiomeTrackerGui"
screenGui.ResetOnSpawn = false
screenGui.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
screenGui.Parent = playerGui

local frame = Instance.new("Frame")
frame.Name = "MainFrame"
frame.Size = UDim2.fromOffset(240, 0)
frame.AutomaticSize = Enum.AutomaticSize.Y
frame.Position = UDim2.new(0.82, 0, 0.20, 0)
frame.BackgroundColor3 = Color3.fromRGB(15, 17, 23)
frame.BackgroundTransparency = 0.25
frame.BorderSizePixel = 0
frame.Active = true
frame.Parent = screenGui
addCorner(frame, 16)
addGlassStroke(frame, 0.7, 1)
addGlassGradient(frame)

local framePadding = Instance.new("UIPadding")
framePadding.PaddingTop = UDim.new(0, 12)
framePadding.PaddingBottom = UDim.new(0, 12)
framePadding.PaddingLeft = UDim.new(0, 12)
framePadding.PaddingRight = UDim.new(0, 12)
framePadding.Parent = frame

local listLayout = Instance.new("UIListLayout")
listLayout.SortOrder = Enum.SortOrder.LayoutOrder
listLayout.Padding = UDim.new(0, 6)
listLayout.Parent = frame

local titleLabel = Instance.new("TextLabel")
titleLabel.Name = "Title"
titleLabel.Size = UDim2.new(1, 0, 0, 20)
titleLabel.BackgroundTransparency = 1
titleLabel.Text = "Biome Counter"
titleLabel.TextColor3 = Color3.fromRGB(240, 243, 250)
titleLabel.Font = Enum.Font.GothamBold
titleLabel.TextSize = 14
titleLabel.TextXAlignment = Enum.TextXAlignment.Left
titleLabel.LayoutOrder = 1
titleLabel.Parent = frame

local currentBiomeLabel = Instance.new("TextLabel")
currentBiomeLabel.Name = "CurrentBiomeLabel"
currentBiomeLabel.Size = UDim2.new(1, 0, 0, 16)
currentBiomeLabel.BackgroundTransparency = 1
currentBiomeLabel.Text = "Current: Normal"
currentBiomeLabel.TextColor3 = Color3.fromRGB(160, 168, 185)
currentBiomeLabel.Font = Enum.Font.GothamMedium
currentBiomeLabel.TextSize = 11
currentBiomeLabel.TextXAlignment = Enum.TextXAlignment.Left
currentBiomeLabel.LayoutOrder = 2
currentBiomeLabel.Parent = frame

-- Container Grid Framework
local buttonGridFrame = Instance.new("Frame")
buttonGridFrame.Name = "ButtonGrid"
buttonGridFrame.Size = UDim2.new(1, 0, 0, 0)
buttonGridFrame.AutomaticSize = Enum.AutomaticSize.Y
buttonGridFrame.BackgroundTransparency = 1
buttonGridFrame.LayoutOrder = 3
buttonGridFrame.Parent = frame

local gridLayout = Instance.new("UIListLayout")
gridLayout.SortOrder = Enum.SortOrder.LayoutOrder
gridLayout.Padding = UDim.new(0, 5)
gridLayout.Parent = buttonGridFrame
-- ===== BIOME LOGS & GUI SYSTEM (PART 4 OF 4 - WITH TEXT OUTLINES) =====

-- Tally UI Core Button Node Generator
local uiButtons = {}
for idx, config in ipairs(BIOME_CONFIG) do
    local biomeBtn = Instance.new("TextButton")
    biomeBtn.Name = config.ID .. "Button"
    biomeBtn.Size = UDim2.new(1, 0, 0, 32)
    biomeBtn.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
    biomeBtn.BackgroundTransparency = 0.94
    biomeBtn.BorderSizePixel = 0
    biomeBtn.Text = string.format("  %s: 0  [ON]", config.Text)
    biomeBtn.TextColor3 = config.Color
    biomeBtn.Font = Enum.Font.GothamSemibold
    biomeBtn.TextSize = 12
    biomeBtn.TextXAlignment = Enum.TextXAlignment.Left
    biomeBtn.AutoButtonColor = false
    biomeBtn.LayoutOrder = idx
    biomeBtn.Parent = buttonGridFrame
    addCorner(biomeBtn, 8)
    addGlassStroke(biomeBtn, 0.85, 1)

    -- Dynamic Anti-Glare Text Outline for the button contents
    local textStroke = Instance.new("UIStroke")
    textStroke.Color = Color3.fromRGB(10, 12, 16)      -- Dark outline layer
    textStroke.Thickness = 1.2                         -- Thin shell so it doesn't pixelate fonts
    textStroke.Transparency = 0.2                      -- Slightly transparent blend
    textStroke.ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual -- Binds outline directly to text characters
    textStroke.Parent = biomeBtn

    -- Toggle Engine Handler Hook
    biomeBtn.MouseButton1Click:Connect(function()
        _G.BiomeFilterStates[config.ID] = not _G.BiomeFilterStates[config.ID]
        local modeStr = _G.BiomeFilterStates[config.ID] and "ON" or "OFF"
        
        biomeBtn.BackgroundTransparency = _G.BiomeFilterStates[config.ID] and 0.94 or 0.97
        biomeBtn.Text = string.format("  %s: %d  [%s]", config.Text, biomeCounters[config.ID], modeStr)
    end)

    uiButtons[config.ID] = biomeBtn
end

-- 4. REAL-TIME DATA PROCESSING PIPELINE
local function handleBiomeDetection(detectedString)
    -- Check if it's an ending message first
    if string.find(detectedString, "Normal") then
        currentBiomeLabel.Text = "Current: Normal"
        currentBiomeLabel.TextColor3 = Color3.fromRGB(160, 168, 185)
        return
    end

    -- Process standard tally updates
    local targetID = detectedString
    if biomeCounters[targetID] ~= nil then
        biomeCounters[targetID] += 1
        
        local matchConfig = nil
        for _, config in ipairs(BIOME_CONFIG) do
            if config.ID == targetID then
                matchConfig = config
                break
            end
        end

        if matchConfig then
            currentBiomeLabel.Text = "Current: " .. matchConfig.Text
            currentBiomeLabel.TextColor3 = matchConfig.Color
            
            local activeMode = _G.BiomeFilterStates[targetID] and "ON" or "OFF"
            uiButtons[targetID].Text = string.format("  %s: %d  [%s]", matchConfig.Text, biomeCounters[targetID], activeMode)
        end
    end
end

-- Intercept and map messages via new pipeline
TextChatService.OnIncomingMessage = function(message)
    if message.Text and message.Text ~= "" then
        for pattern, biomeID in pairs(BIOME_DICTIONARY) do
            if string.find(message.Text, escapePattern(pattern)) then
                handleBiomeDetection(biomeID)
                break
            end
        end
    end
end
print("Biome Tracker fully initiated with readable text outlines!")


-- ===== GuiDragging.lua =====
-- DRAGGING

local dragging = false
local dragStart = nil
local frameStart = nil

frame.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1
        or input.UserInputType == Enum.UserInputType.Touch then

        dragging = true
        dragStart = input.Position
        frameStart = frame.Position
    end
end)

UserInputService.InputChanged:Connect(function(input)
    if not dragging or not dragStart or not frameStart then
        return
    end

    if input.UserInputType == Enum.UserInputType.MouseMovement
        or input.UserInputType == Enum.UserInputType.Touch then

        local delta = input.Position - dragStart
        frame.Position = UDim2.new(
            frameStart.X.Scale,
            frameStart.X.Offset + delta.X,
            frameStart.Y.Scale,
            frameStart.Y.Offset + delta.Y
        )
    end
end)

UserInputService.InputEnded:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1
        or input.UserInputType == Enum.UserInputType.Touch then

        dragging = false
        dragStart = nil
        frameStart = nil
    end
end)

-- ===== PathContextMenu.lua =====
-- PATH SETTINGS DROPDOWN (RIGHT-CLICK MENU)

local contextMenu = Instance.new("Frame")
contextMenu.Name = "PathContextMenu"
contextMenu.Size = UDim2.fromOffset(200, 168)
contextMenu.BackgroundColor3 = Color3.fromRGB(12, 14, 20)
contextMenu.BackgroundTransparency = 0.15
contextMenu.BorderSizePixel = 0
contextMenu.Visible = false
contextMenu.ZIndex = 20
contextMenu.Parent = screenGui
addCorner(contextMenu, 12)
addGlassStroke(contextMenu, 0.75, 1)
addGlassGradient(contextMenu)

local viewPathButton = Instance.new("TextButton")
viewPathButton.Name = "ViewPathButton"
viewPathButton.Size = UDim2.new(1, -10, 0, 34)
viewPathButton.Position = UDim2.fromOffset(5, 5)
viewPathButton.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
viewPathButton.BackgroundTransparency = 0.94
viewPathButton.BorderSizePixel = 0
viewPathButton.TextColor3 = Color3.fromRGB(230, 235, 245)
viewPathButton.Font = Enum.Font.GothamMedium
viewPathButton.TextSize = 11
viewPathButton.TextXAlignment = Enum.TextXAlignment.Left
viewPathButton.AutoButtonColor = false
viewPathButton.ZIndex = 21
viewPathButton.Parent = contextMenu
addCorner(viewPathButton, 8)

local autoJumpButton = Instance.new("TextButton")
autoJumpButton.Name = "AutoJumpButton"
autoJumpButton.Size = UDim2.new(1, -10, 0, 34)
autoJumpButton.Position = UDim2.fromOffset(5, 44)
autoJumpButton.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
autoJumpButton.BackgroundTransparency = 0.94
autoJumpButton.BorderSizePixel = 0
autoJumpButton.TextColor3 = Color3.fromRGB(230, 235, 245)
autoJumpButton.Font = Enum.Font.GothamMedium
autoJumpButton.TextSize = 11
autoJumpButton.TextXAlignment = Enum.TextXAlignment.Left
autoJumpButton.AutoButtonColor = false
autoJumpButton.ZIndex = 21
autoJumpButton.Parent = contextMenu
addCorner(autoJumpButton, 8)

local autoEquipButton = Instance.new("TextButton")
autoEquipButton.Name = "AutoEquipButton"
autoEquipButton.Size = UDim2.new(1, -10, 0, 34)
autoEquipButton.Position = UDim2.fromOffset(5, 83)
autoEquipButton.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
autoEquipButton.BackgroundTransparency = 0.94
autoEquipButton.BorderSizePixel = 0
autoEquipButton.TextColor3 = Color3.fromRGB(230, 235, 245)
autoEquipButton.Font = Enum.Font.GothamMedium
autoEquipButton.TextSize = 11
autoEquipButton.TextXAlignment = Enum.TextXAlignment.Left
autoEquipButton.AutoButtonColor = false
autoEquipButton.ZIndex = 21
autoEquipButton.Parent = contextMenu
addCorner(autoEquipButton, 8)

local function updateMenuTexts()
    viewPathButton.Text = viewPathEnabled
        and "   ✓   View Pathfind Path"
        or "   □   View Pathfind Path"

    autoJumpButton.Text = autoJumpEnabled
        and "   ✓   Constant Auto-Jump"
        or "   □   Constant Auto-Jump"

    autoEquipButton.Text = autoEquipEnabled
        and "   ✓   Auto-Equip Aura"
        or "   □   Auto-Equip Aura"
end

updateMenuTexts()

-- ===== UiStateController.lua =====
-- UI STATE CONTROLLER

local function setStatus(text, color)
    statusLabel.Text = "Status: " .. text
    statusLabel.TextColor3 = color or Color3.fromRGB(160, 168, 185)
end

local function updateBoxesToggle()
    toggleBoxesButton.Text = boxesEnabled and "Bounding Boxes: ON" or "Bounding Boxes: OFF"
    toggleBoxesButton.BackgroundTransparency = boxesEnabled and 0.88 or 0.95
end

local function updatePathToggle()
    togglePathButton.Text = pathfindingEnabled and "Pathfinding: ON" or "Pathfinding: OFF"
    togglePathButton.BackgroundTransparency = pathfindingEnabled and 0.84 or 0.95
end

local function updateDeviceToggle()
    autoDeviceButton.Text = autoDeviceEnabled and "Auto-Device: ON" or "Auto-Device: OFF"
    autoDeviceButton.BackgroundTransparency = autoDeviceEnabled and 0.84 or 0.95
end

updateDeviceToggle()
updateBoxesToggle()
updatePathToggle()

-- ===== PathVisualization.lua =====
-- PATH VISUALIZATION

local function clearPathVisuals()
    for _, item in ipairs(pathVisualFolder:GetChildren()) do
        item:Destroy()
    end
end

local function createPathPoint(position, index)
    local point = Instance.new("Part")
    point.Name = "Waypoint_" .. index
    point.Shape = Enum.PartType.Ball
    point.Size = Vector3.new(0.4, 0.4, 0.4)
    point.Position = position + Vector3.new(0, 0.25, 0)
    point.Anchored = true
    point.CanCollide = false
    point.CanTouch = false
    point.CanQuery = false
    point.Material = Enum.Material.Neon
    point.Color = PATH_COLOR
    point.Transparency = 0.2
    point.Parent = pathVisualFolder
end

local function createPathLine(a, b, index)
    local distance = (b - a).Magnitude
    if distance <= 0 then
        return
    end

    local segment = Instance.new("Part")
    segment.Name = "Segment_" .. index
    segment.Size = Vector3.new(0.1, 0.1, distance)
    segment.CFrame = CFrame.lookAt((a + b) / 2, b)
    segment.Anchored = true
    segment.CanCollide = false
    segment.CanTouch = false
    segment.CanQuery = false
    segment.Material = Enum.Material.Neon
    segment.Color = PATH_COLOR
    segment.Transparency = 0.35
    segment.Parent = pathVisualFolder
end

local function drawPath(path)
    clearPathVisuals()

    if not viewPathEnabled then
        return
    end

    local waypoints = path:GetWaypoints()
    for index, waypoint in ipairs(waypoints) do
        createPathPoint(waypoint.Position, index)

        if index > 1 then
            createPathLine(waypoints[index - 1].Position, waypoint.Position, index)
        end
    end
end

-- ===== WatermelonTracker.lua =====
-- WATERMELON BOUNDING BOX TRACKER

local function getModelBounds(object)
    if object:IsA("Model") then
        if object.PrimaryPart or object:FindFirstChildWhichIsA("BasePart", true) then
            return object:GetBoundingBox()
        end
    elseif object:IsA("BasePart") then
        return object.CFrame, object.Size
    end

    return nil, nil
end

local function removeTrackedWatermelon(object)
    local data = trackedWatermelons[object]
    if not data then
        return
    end

    if data.Anchor and data.Anchor.Parent then
        data.Anchor:Destroy()
    end

    trackedWatermelons[object] = nil
end

local function markWatermelon(object)
    if trackedWatermelons[object] then
        return
    end

    local boundsCFrame, boundsSize = getModelBounds(object)
    if not boundsCFrame or not boundsSize then
        return
    end

    local anchor = Instance.new("Part")
    anchor.Name = "_WatermelonAnchor"
    anchor.Size = boundsSize
    anchor.CFrame = boundsCFrame
    anchor.Anchored = true
    anchor.CanCollide = false
    anchor.CanTouch = false
    anchor.CanQuery = false
    anchor.Transparency = 1
    anchor.Parent = visualFolder

    local box = Instance.new("BoxHandleAdornment")
    box.Name = "_WatermelonBox"
    box.Adornee = anchor
    box.Size = boundsSize + Vector3.new(0.12, 0.12, 0.12)
    box.Color3 = BOX_COLOR
    box.Transparency = 0.65
    box.AlwaysOnTop = true
    box.ZIndex = 10
    box.Visible = boxesEnabled
    box.Parent = anchor

    local outline = Instance.new("BoxHandleAdornment")
    outline.Name = "_WatermelonOutline"
    outline.Adornee = anchor
    outline.Size = boundsSize + Vector3.new(0.25, 0.25, 0.25)
    outline.Color3 = OUTLINE_COLOR
    outline.Transparency = 0.25
    outline.AlwaysOnTop = true
    outline.ZIndex = 11
    outline.Visible = boxesEnabled
    outline.Parent = anchor

    trackedWatermelons[object] = {
        Anchor = anchor,
        Box = box,
        Outline = outline,
    }

    object.Destroying:Connect(function()
        removeTrackedWatermelon(object)
    end)

    object.AncestryChanged:Connect(function()
        if not object:IsDescendantOf(Workspace) then
            removeTrackedWatermelon(object)
        end
    end)
end

local function checkObject(object)
    if string.lower(object.Name) ~= WATERMELON_NAME then
        return
    end

    if object:IsA("Model") then
        markWatermelon(object)
        return
    end

    local model = object:FindFirstAncestorWhichIsA("Model")
    if model and model ~= Workspace then
        markWatermelon(model)
    else
        markWatermelon(object)
    end
end

local function setBoxesVisible(enabled)
    boxesEnabled = enabled
    updateBoxesToggle()

    for _, data in pairs(trackedWatermelons) do
        data.Box.Visible = enabled
        data.Outline.Visible = enabled
    end
end

toggleBoxesButton.MouseButton1Click:Connect(function()
    setBoxesVisible(not boxesEnabled)
end)

for _, object in ipairs(Workspace:GetDescendants()) do
    checkObject(object)
end

Workspace.DescendantAdded:Connect(checkObject)

task.spawn(function()
    while screenGui.Parent do
        task.wait(SCAN_INTERVAL)

        for _, object in ipairs(Workspace:GetDescendants()) do
            checkObject(object)
        end

        for object, _ in pairs(trackedWatermelons) do
            if not object.Parent or not object:IsDescendantOf(Workspace) then
                removeTrackedWatermelon(object)
            end
        end
    end
end)

-- ===== InteractionHelpers.lua =====
-- GAME INTERACTION HELPER FUNCTIONS

local function clickGiveUpButton()
    local mainInterface = playerGui:FindFirstChild("MainInterface")
    if not mainInterface then return false end

    for _, obj in ipairs(mainInterface:GetDescendants()) do
        if obj:IsA("ImageButton") or obj:IsA("TextButton") then
            local textLabel = obj:FindFirstChildWhichIsA("TextLabel", true)
            if (textLabel and string.find(string.lower(textLabel.Text), "give up")) or
               (obj:IsA("TextButton") and string.find(string.lower(obj.Text), "give up")) then

                setStatus("Giving Up...", Color3.fromRGB(240, 190, 140))

                if typeof(getconnections) == "function" then
                    for _, conn in ipairs(getconnections(obj.Activated)) do
                        if conn.Function then conn.Function() end
                    end
                    for _, conn in ipairs(getconnections(obj.MouseButton1Click)) do
                        if conn.Function then conn.Function() end
                    end
                end

                local pos = obj.AbsolutePosition
                local size = obj.AbsoluteSize
                local inset, _ = GuiService:GetGuiInset()

                local clickX = pos.X + (size.X / 2) + inset.X
                local clickY = pos.Y + (size.Y / 2) + inset.Y

                VirtualInputManager:SendMouseButtonEvent(clickX, clickY, 0, true, game, 0)
                task.wait(0.05)
                VirtualInputManager:SendMouseButtonEvent(clickX, clickY, 0, false, game, 0)

                consecutivePathFailures = 0
                return true
            end
        end
    end
    return false
end

local function findChoiceButtonByText(targetText)
    local mainInterface = playerGui:FindFirstChild("MainInterface")
    if not mainInterface then return nil end

    local dialog = mainInterface:FindFirstChild("Dialog")
    if not dialog then return nil end

    local choices = dialog:FindFirstChild("Choices")
    if not choices then return nil end

    for _, obj in ipairs(choices:GetChildren()) do
        if obj:IsA("TextButton") and obj.Text == targetText then
            return obj
        end
    end
    return nil
end

local function waitForChoiceButton(targetText, timeout, token)
    local startTime = os.clock()
    repeat
        if pathfindingEnabled == false or routineToken ~= token then return nil end
        local button = findChoiceButtonByText(targetText)
        if button then return button end
        task.wait(0.25)
    until os.clock() - startTime >= timeout
    return nil
end

local function clickChoiceButton(button)
    if not button then return end

    if typeof(getconnections) == "function" then
        for _, connection in ipairs(getconnections(button.Activated)) do
            if connection.Function then connection.Function() end
        end
        for _, connection in ipairs(getconnections(button.MouseButton1Click)) do
            if connection.Function then connection.Function() end
        end
    end

    local pos = button.AbsolutePosition
    local size = button.AbsoluteSize
    local inset, _ = GuiService:GetGuiInset()

    local clickX = pos.X + (size.X / 2) + inset.X
    local clickY = pos.Y + (size.Y / 2) + inset.Y

    VirtualInputManager:SendMouseButtonEvent(clickX, clickY, 0, true, game, 0)
    task.wait(0.05)
    VirtualInputManager:SendMouseButtonEvent(clickX, clickY, 0, false, game, 0)
end

-- ===== WatermelonPromptHandler.lua =====
-- PROXIMITY PROMPT & WATERMELON SEARCH

local function triggerPromptEnhanced(prompt)
    if not prompt then return end

    local char = player.Character
    local rootPart = char and char:FindFirstChild("HumanoidRootPart")

    if rootPart and prompt.Parent then
        local targetPart = prompt.Parent
        if targetPart:IsA("Attachment") then targetPart = targetPart.Parent end
        if targetPart and targetPart:IsA("BasePart") then
            rootPart.CFrame = CFrame.new(rootPart.Position, Vector3.new(targetPart.Position.X, rootPart.Position.Y, targetPart.Position.Z))
        end
    end

    task.wait(0.1)
    prompt.HoldDuration = 0

    if typeof(fireproximityprompt) == "function" then
        fireproximityprompt(prompt)
    end

    prompt:InputHoldBegin()
    task.wait(0.05)
    prompt:InputHoldEnd()
end

local function findWatermelonPrompt()
    local topWatermelon = Workspace:FindFirstChild("Watermelon")
    if topWatermelon then
        local innerWatermelon = topWatermelon:FindFirstChild("Watermelon")
        if innerWatermelon then
            local attachment = innerWatermelon:FindFirstChild("Attachment")
            if attachment then
                local prompt = attachment:FindFirstChildWhichIsA("ProximityPrompt")
                if prompt then return prompt, innerWatermelon end
            end
        end
    end

    for targetModel, _ in pairs(trackedWatermelons) do
        local prompt = targetModel:FindFirstChildWhichIsA("ProximityPrompt", true)
        if prompt then
            local part = targetModel:FindFirstChildWhichIsA("BasePart", true) or targetModel.PrimaryPart
            return prompt, part
        end
    end

    for _, obj in ipairs(Workspace:GetDescendants()) do
        if obj:IsA("ProximityPrompt") and string.find(string.lower(obj.Parent.Name), "watermelon") then
            local part = obj.Parent
            if part:IsA("BasePart") then
                return obj, part
            end
        end
    end

    return nil, nil
end

local function spamPromptUntilRemoved(prompt, watermelonPart, token)
    if not prompt or not watermelonPart then return end

    local removed = false
    local destroyConn = watermelonPart.Destroying:Connect(function()
        removed = true
    end)

    local rotSpeed = math.rad(120)
    local startTime = os.clock()

    setStatus("Collecting Watermelon...", Color3.fromRGB(200, 225, 255))

    while not removed and watermelonPart.Parent and pathfindingEnabled and routineToken == token do
        prompt:InputHoldBegin()
        task.wait(0.05)
        prompt:InputHoldEnd()

        if typeof(fireproximityprompt) == "function" then
            fireproximityprompt(prompt)
        end

        local now = os.clock()
        if Camera then
            local center = watermelonPart.Position
            local radius = 6
            local angle = (now - startTime) * rotSpeed

            local newX = center.X + math.cos(angle) * radius
            local newZ = center.Z + math.sin(angle) * radius

            Camera.CFrame = CFrame.new(
                Vector3.new(newX, center.Y + 3, newZ),
                center
            )
        end

        task.wait(0.05)
    end

    if destroyConn then destroyConn:Disconnect() end
end

local function isWithinPromptRange(prompt, watermelonPart)
    if not prompt or not watermelonPart then return false end

    local char = player.Character
    if not char then return false end

    local rootPart = char:FindFirstChild("HumanoidRootPart")
    if not rootPart then return false end

    local maxDist = prompt.MaxActivationDistance or 10
    return (rootPart.Position - watermelonPart.Position).Magnitude <= maxDist
end

-- ===== AutoEquip.lua =====
-- ===== AutoEquip_Optimized.lua =====
-- AUTO EQUIP ABYSSAL HUNTER (PACKET INJECTION ONLY)

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Players = game:GetService("Players")

local LocalPlayer = Players.LocalPlayer
local ByteNetEvent = ReplicatedStorage:WaitForChild("ByteNetReliable")

local AUTO_EQUIP_RETRY_INTERVAL = 15

-- Packs and dispatches a raw byte array directly to the engine
local function fireEquipPacket(bytes)
    local packetBuffer = buffer.create(#bytes)
    for i = 1, #bytes do
        buffer.writeu8(packetBuffer, i - 1, bytes[i])
    end
    ByteNetEvent:FireServer(packetBuffer, nil)
end

local function executeEquipCycle()
    if not autoEquipEnabled then
        return
    end

    -- Send the alternative packet
    fireEquipPacket({ 135, 64, 0, 0 })
    task.wait(0.1) -- Brief delay to let the server process the first swap
    
    -- Immediately swap back to the target aura packet
    fireEquipPacket({ 135, 62, 0, 0 })
end

-- Non-blocking constant execution loop
task.spawn(function()
    while true do
        executeEquipCycle()
        task.wait(AUTO_EQUIP_RETRY_INTERVAL)
    end
end)


-- ===== AutoDevice.lua =====
-- ===== AUTO-DEVICE LOGIC (PACKET INJECTION ONLY) =====

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ByteNetEvent = ReplicatedStorage:WaitForChild("ByteNetReliable")

local BIOME_INTERVAL = 5 * 60  -- 30 minutes
local STRANGE_INTERVAL = 5 * 60  -- 20 minutes

-- Generic function to build and send the requested byte stream
local function fireDevicePacket(bytes)
    local packetBuffer = buffer.create(#bytes)
    for i = 1, #bytes do
        buffer.writeu8(packetBuffer, i - 1, bytes[i])
    end
    ByteNetEvent:FireServer(packetBuffer, nil)
end

local function runBiomeRandomizerLoop()
    while true do
        if autoDeviceEnabled then
            -- Direct packet injection for Biome Randomizer
            fireDevicePacket({ 34, 1, 0, 0, 0, 16, 0, 66, 105, 111, 109, 101, 32, 82, 97, 110, 100, 111, 109, 105, 122, 101, 114 })
        end
        task.wait(BIOME_INTERVAL)
    end
end

local function runStrangeControllerLoop()
    while true do
        if autoDeviceEnabled then
            -- Direct packet injection for Strange Controller
            fireDevicePacket({ 34, 1, 0, 0, 0, 18, 0, 83, 116, 114, 97, 110, 103, 101, 32, 67, 111, 110, 116, 114, 111, 108, 108, 101, 114 })
        end
        task.wait(STRANGE_INTERVAL)
    end
end

-- Start the constant non-blocking loops
task.spawn(runBiomeRandomizerLoop)
task.spawn(runStrangeControllerLoop)


-- ===== PathfindingEngine.lua =====
-- PATHFINDING & UNSTUCK ENGINE

local function shouldContinue(token)
    return pathfindingEnabled and routineToken == token
end

local function attemptUnstuck(humanoid, rootPart)
    setStatus("Unsticking character...", Color3.fromRGB(240, 200, 120))

    humanoid.Jump = true
    local moveBackVector = -rootPart.CFrame.LookVector * 6 + Vector3.new(math.random(-4, 4), 0, math.random(-4, 4))
    humanoid:MoveTo(rootPart.Position + moveBackVector)

    task.wait(0.8)
end

local function walkToPosition(targetPosition, token)
    local character = player.Character
    if not character then return false end

    local humanoid = character:FindFirstChildOfClass("Humanoid")
    local rootPart = character:FindFirstChild("HumanoidRootPart")
    if not humanoid or not rootPart then return false end

    while shouldContinue(token) do
        if consecutivePathFailures >= MAX_CONSECUTIVE_FAILURES then
            clickGiveUpButton()
            return false
        end

        local effectiveTarget = targetPosition
        if consecutivePathFailures >= 3 then
            local detourOffset = Vector3.new(
                math.random(-12, 12),
                0,
                math.random(-12, 12)
            )
            effectiveTarget = targetPosition + detourOffset
        elseif consecutivePathFailures > 0 then
            local lightOffset = Vector3.new(
                math.random(-4, 4),
                0,
                math.random(-4, 4)
            )
            effectiveTarget = targetPosition + lightOffset
        end

        local path = PathfindingService:CreatePath(PATH_OPTIONS)
        local computed = pcall(function()
            path:ComputeAsync(rootPart.Position, effectiveTarget)
        end)

        if not computed or path.Status ~= Enum.PathStatus.Success then
            consecutivePathFailures += 1
            setStatus("Path failed (" .. consecutivePathFailures .. "/" .. MAX_CONSECUTIVE_FAILURES .. ")", Color3.fromRGB(240, 140, 150))

            if consecutivePathFailures >= MAX_CONSECUTIVE_FAILURES then
                clickGiveUpButton()
                return false
            end

            attemptUnstuck(humanoid, rootPart)
        else
            drawPath(path)
            setStatus("Walking...", Color3.fromRGB(180, 220, 255))

            local waypoints = path:GetWaypoints()

            local autoJumpConn = nil
            if autoJumpEnabled then
                autoJumpConn = RunService.PreRender:Connect(function()
                    if humanoid and humanoid.Health > 0 then
                        humanoid.Jump = true
                    end
                end)
            end

            local stepFailed = false
            for _, waypoint in ipairs(waypoints) do
                if not shouldContinue(token) or humanoid.Health <= 0 then
                    if autoJumpConn then autoJumpConn:Disconnect() end
                    return false
                end

                if waypoint.Action == Enum.PathWaypointAction.Jump and not autoJumpEnabled then
                    humanoid.Jump = true
                end

                humanoid:MoveTo(waypoint.Position)

                local reached = false
                local finished = false

                local moveConnection = humanoid.MoveToFinished:Connect(function(result)
                    reached = result
                    finished = true
                end)

                local startedAt = os.clock()

                while not finished and shouldContinue(token) do
                    if os.clock() - startedAt >= 6 then
                        break
                    end
                    RunService.Heartbeat:Wait()
                end

                if moveConnection then moveConnection:Disconnect() end

                if not reached then
                    if autoJumpConn then autoJumpConn:Disconnect() end
                    consecutivePathFailures += 1
                    setStatus("Stuck (" .. consecutivePathFailures .. "/" .. MAX_CONSECUTIVE_FAILURES .. ")", Color3.fromRGB(240, 140, 150))

                    attemptUnstuck(humanoid, rootPart)
                    stepFailed = true
                    break
                end
            end

            if autoJumpConn then autoJumpConn:Disconnect() end

            if not stepFailed then
                consecutivePathFailures = 0
                setStatus("Reached target", Color3.fromRGB(200, 230, 255))
                return true
            end
        end
    end

    return false
end

-- ===== AutomationSequences.lua =====
-- AUTOMATION SEQUENCES

local plr = game.Players.LocalPlayer

local function resetPlr()
    if plr.Character then
        plr.Character:BreakJoints()
    end
end

local function getLimeTarget()
    local mapFolder = Workspace:WaitForChild("Map", 5)
    if not mapFolder then return nil, nil, nil end

    local limeModel = mapFolder:WaitForChild("Lime", 5)
    if not limeModel then return nil, nil, nil end

    local torso = limeModel:WaitForChild("Torso", 5)
    if not torso then return nil, nil, nil end

    return limeModel, torso.Position, torso:FindFirstChildWhichIsA("ProximityPrompt")
end

local function startWatermelonMinigameSequence(token)
    setStatus("Searching Watermelon...", Color3.fromRGB(240, 220, 160))
    local targetPrompt, watermelonPart = findWatermelonPrompt()
    local startTime = os.clock()

    while not targetPrompt and shouldContinue(token) do
        -- WATERMELON SEARCH TIMEOUT: If looking for more than 3 minutes (180s), give up
        if os.clock() - startTime > 180 then
            setStatus("Search timeout! Giving up...", Color3.fromRGB(255, 100, 100))
            clickGiveUpButton()
            return
        end

        task.wait(0.5)
        targetPrompt, watermelonPart = findWatermelonPrompt()
    end

    if not targetPrompt or not shouldContinue(token) then
        setStatus("Watermelon missing", Color3.fromRGB(240, 140, 150))
        task.wait(2)
        return
    end

    if watermelonPart and watermelonPart:IsA("BasePart") then
        walkToPosition(watermelonPart.Position, token)
    end

    if not shouldContinue(token) then return end

    task.wait(0.3)
    local freshPrompt, freshPart = findWatermelonPrompt()
    freshPrompt = freshPrompt or targetPrompt
    freshPart = freshPart or watermelonPart

    if freshPrompt and freshPart then
        if not isWithinPromptRange(freshPrompt, freshPart) then
            walkToPosition(freshPart.Position, token)
            task.wait(0.3)

            local recheckPrompt, recheckPart = findWatermelonPrompt()
            freshPrompt = recheckPrompt or freshPrompt
            freshPart = recheckPart or freshPart
        end

        if isWithinPromptRange(freshPrompt, freshPart) and shouldContinue(token) then
            spamPromptUntilRemoved(freshPrompt, freshPart, token)
        end
    end

    updateAttemptsUI()

    task.wait(1)
end

local function executeRoutine(token)
    if not shouldContinue(token) then return end

    local _, limePos, limePrompt = getLimeTarget()
    if not limePos or not limePrompt then
        setStatus("Waiting for Lime...", Color3.fromRGB(160, 168, 185))
        task.wait(1)
        return
    end

    if walkToPosition(limePos, token) then
        if not shouldContinue(token) then return end

        setStatus("Interacting with Lime...", Color3.fromRGB(240, 220, 160))
        triggerPromptEnhanced(limePrompt)

        task.wait(2)
        if not shouldContinue(token) then return end

        -- LIME CONVERSATION STUCK CHECK
        local conversationStartTime = os.clock()

        local minigameBtn = waitForChoiceButton("[ Minigame ]", 8, token)
        
        if not minigameBtn then
            if os.clock() - conversationStartTime > 60 then
                setStatus("Stuck on Lime! Resetting...", Color3.fromRGB(255, 100, 100))
                resetPlr()
                task.wait(5)
                return
            end
        end

        if minigameBtn then
            task.wait(0.5)
            clickChoiceButton(minigameBtn)

            local ticketBtn = waitForChoiceButton("[ -1 Minigame Ticket ]", 8, token)
            
            if not ticketBtn then
                if os.clock() - conversationStartTime > 60 then
                    setStatus("Stuck on Ticket! Resetting...", Color3.fromRGB(255, 100, 100))
                    resetPlr()
                    task.wait(5)
                    return
                end
            end

            if ticketBtn then
                task.wait(0.5)
                clickChoiceButton(ticketBtn)

                task.wait(1)
                if shouldContinue(token) then
                    startWatermelonMinigameSequence(token)
                end
            end
        end
    end
end


-- ===== ControllerExecution.lua =====
-- CONTROLLER EXECUTION & TOGGLES

local function stopRoutine()
    routineToken += 1
    clearPathVisuals()
    setStatus("Idle", Color3.fromRGB(160, 168, 185))
end

local function startRoutineLoop()
    routineToken += 1
    local currentToken = routineToken

    task.spawn(function()
        while pathfindingEnabled and routineToken == currentToken do
            executeRoutine(currentToken)
            task.wait(0.5)
        end
    end)
end

togglePathButton.MouseButton1Click:Connect(function()
    pathfindingEnabled = not pathfindingEnabled
    updatePathToggle()

    if pathfindingEnabled then
        startRoutineLoop()
    else
        stopRoutine()
    end
end)

togglePathButton.MouseButton2Click:Connect(function()
    contextMenu.Position = UDim2.fromOffset(
        togglePathButton.AbsolutePosition.X + togglePathButton.AbsoluteSize.X + 5,
        togglePathButton.AbsolutePosition.Y
    )
    contextMenu.Visible = not contextMenu.Visible
end)

viewPathButton.MouseButton1Click:Connect(function()
    viewPathEnabled = not viewPathEnabled
    updateMenuTexts()
    if not viewPathEnabled then
        clearPathVisuals()
    end
end)

autoJumpButton.MouseButton1Click:Connect(function()
    autoJumpEnabled = not autoJumpEnabled
    updateMenuTexts()
end)

autoEquipButton.MouseButton1Click:Connect(function()
    autoEquipEnabled = not autoEquipEnabled
    updateMenuTexts()
end)

autoDeviceButton.MouseButton1Click:Connect(function()
    autoDeviceEnabled = not autoDeviceEnabled
    updateDeviceToggle()
end)

UserInputService.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 then
        if contextMenu.Visible then
            local mousePos = UserInputService:GetMouseLocation()
            local menuPos = contextMenu.AbsolutePosition
            local menuSize = contextMenu.AbsoluteSize

            if mousePos.X < menuPos.X or mousePos.X > menuPos.X + menuSize.X
                or mousePos.Y < menuPos.Y or mousePos.Y > menuPos.Y + menuSize.Y then

                contextMenu.Visible = false
            end
        end
    end
end)
